// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeveloperNews
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "0298784e-e549-4e67-b3f3-af01a28a9f88";
        public static Guid Package = new Guid(PackageString);

        public const string PackageCommandSetString = "2275760e-e992-461e-ae66-2e42f176d277";
        public static Guid PackageCommandSet = new Guid(PackageCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PackageGroup = 0xB000;
        public const int DeveloperNewsCommand = 0x0210;
        public const int PackageOptionsCommand = 0x0215;
    }
}