// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeveloperNews
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "6dd5e0a2-9ddd-415e-a92b-ffb8030544fd";
        public static Guid Package = new Guid(PackageString);

        public const string PackageCommandSetString = "caff25ce-14c9-4f66-8c70-5eb3f05e259b";
        public static Guid PackageCommandSet = new Guid(PackageCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PackageGroup = 0xB000;
        public const int ViewDeveloperNews = 0x0210;
        public const int ViewDeveloperNewsOptions = 0x0215;
    }
}