// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeveloperNews
{
    internal sealed partial class Vsix
    {
        public const string Id = "DB0B2617-846F-4867-9D3C-E22A094DD21B";
        public const string Name = "Developer News";
        public const string Description = @"Developer News brought back to VS 2019";
        public const string Language = "en-US";
        public const string Version = "0.1.1";
        public const string Author = "Yann Duran";
        public const string Tags = "developer news";
    }
}
