// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeveloperNews
{
    internal sealed partial class Vsix
    {
        public const string Id = "E35E8D0A-2D8C-4A18-BF10-CB446334A278";
        public const string Name = "Developer News";
        public const string Description = @"Bring Back Developer News!";
        public const string Language = "en-US";
        public const string Version = "1.1.0.3";
        public const string Author = "Yann Duran";
        public const string Tags = "developer news, developer-news, developernews, start page, start-page, startpage, luminous, yannduran, yd";
    }
}
